
export const PUBLIC_SCHEMA_DDL = `
-------------------------------------------------------------------------------
-- 1. PROFILES (Users & Members)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
    id text PRIMARY KEY,
    email text,
    full_name text,
    role text DEFAULT 'user', -- user, admin, support
    tier text DEFAULT 'Free', -- Free, Premium, Pro
    egg_balance jsonb DEFAULT '{"mystery": 0, "premium": 0, "standard": 3}'::jsonb,
    status text DEFAULT 'active', -- active, banned, suspended
    avatar_url text,
    created_at timestamptz DEFAULT now(),
    last_seen timestamptz DEFAULT now(),
    CONSTRAINT profiles_status_check CHECK (status IN ('active', 'inactive', 'banned', 'pending', 'suspended'))
);

-------------------------------------------------------------------------------
-- 2. DROPS (Campaigns)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.drops (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  title text,
  description text,
  status text, -- draft, live, ended
  egg_price int default 0,
  bundle_price int default 0,
  max_supply int,
  
  -- Artist Attribution
  artist_id text,
  artist_name text, 
  
  -- Visual Assets
  banner_path text, -- Stores URL to 'assets' bucket
  
  -- Schedule
  start_at timestamptz,
  end_at timestamptz,
  created_at timestamptz DEFAULT now()
);

-- Patch: Ensure columns exist if table was created previously
ALTER TABLE public.drops ADD COLUMN IF NOT EXISTS artist_name text;
ALTER TABLE public.drops ADD COLUMN IF NOT EXISTS artist_id text;
ALTER TABLE public.drops ADD COLUMN IF NOT EXISTS banner_path text;

-------------------------------------------------------------------------------
-- 3. STAMPS (The Assets)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.stamps (
  id bigint generated by default as identity primary key,
  external_id text unique, -- e.g. 'stp_12345'
  name text,
  slug text,
  rarity text, -- common, rare, foil, legendary, pidgey
  status text, -- draft, ready, active, archived
  collection text,
  
  -- Artist Attribution
  artist_id text,
  artist_name text,
  
  -- Visual Assets & Config
  art_path text, -- Stores URL to 'stamps' bucket
  design_config jsonb, -- Stores Studio settings (border, effects, text overlay)
  
  -- Economics
  price_eggs int default 0,
  edition_count int default 0,
  is_drop_only boolean default false,
  
  created_at timestamptz default now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_stamps_external_id ON public.stamps (external_id);

-- Patch: Ensure columns exist
ALTER TABLE public.stamps ADD COLUMN IF NOT EXISTS artist_name text;
ALTER TABLE public.stamps ADD COLUMN IF NOT EXISTS artist_id text;
ALTER TABLE public.stamps ADD COLUMN IF NOT EXISTS art_path text;
ALTER TABLE public.stamps ADD COLUMN IF NOT EXISTS design_config jsonb;

-------------------------------------------------------------------------------
-- 4. BROADCASTS (Communication)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.broadcasts (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text,
  subject text,
  channels text[], -- email, push, sms
  audience_segment text,
  audience_size int default 0,
  scheduled_at timestamptz,
  status text default 'draft',
  stats jsonb default '{"delivered":0, "opened":0, "clicked":0, "failed":0}'::jsonb,
  created_at timestamptz DEFAULT now()
);

-------------------------------------------------------------------------------
-- 5. PROMOS (Codes & Events)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.promos (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text,
  code text,
  type text, -- discount, egg_bonus
  status text default 'draft',
  description text,
  value jsonb, -- { "percent": 10 } or { "eggs": 5 }
  start_at timestamptz,
  end_at timestamptz,
  usage_count int default 0,
  created_at timestamptz DEFAULT now()
);

-------------------------------------------------------------------------------
-- 6. CARDS (Sent Instances)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cards (
    id text PRIMARY KEY,
    owner_id text,
    data jsonb, -- Stores the template_id, message, recipient info
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-------------------------------------------------------------------------------
-- 7. TRANSACTIONS (Economy Log)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.transactions (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    profile_id text REFERENCES public.profiles(id),
    amount numeric,
    currency text,
    status text,
    description text,
    created_at timestamptz DEFAULT now()
);

-------------------------------------------------------------------------------
-- 8. TICKETS (Support)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tickets (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    profile_id text REFERENCES public.profiles(id),
    subject text,
    status text,
    priority text,
    source text,
    tags text[],
    created_at timestamptz DEFAULT now()
);

-------------------------------------------------------------------------------
-- 9. TICKET MESSAGES
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ticket_messages (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    ticket_id uuid REFERENCES public.tickets(id),
    sender_type text, -- member, admin, system
    sender_id text,
    body text,
    created_at timestamptz DEFAULT now()
);

-------------------------------------------------------------------------------
-- 10. ACTIVITY LOGS
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id text,
    action_type text,
    description text,
    created_at timestamptz DEFAULT now()
);

-------------------------------------------------------------------------------
-- ROW LEVEL SECURITY (RLS) & PERMISSIONS
-------------------------------------------------------------------------------

-- 1. Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stamps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.broadcasts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ticket_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

-- 2. Basic Profiles Policies
CREATE POLICY "Enable read access for all users" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.profiles FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for users based on email" ON public.profiles FOR UPDATE USING (auth.uid()::text = id);

-- 3. Admin "God Mode" Policies (Permissive for Control Tower)
-- In a real app, check for role='admin'. Here we allow authenticated users (the admin) full access.
CREATE POLICY "Admin All Access Drops" ON public.drops FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin All Access Stamps" ON public.stamps FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin All Access Broadcasts" ON public.broadcasts FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin All Access Promos" ON public.promos FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin All Access Cards" ON public.cards FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin All Access Transactions" ON public.transactions FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin All Access Tickets" ON public.tickets FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin All Access Ticket Messages" ON public.ticket_messages FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin All Access Logs" ON public.activity_logs FOR ALL TO authenticated USING (true);

-------------------------------------------------------------------------------
-- STORAGE POLICIES
-------------------------------------------------------------------------------
-- Required Buckets: 'stamps', 'templates', 'assets', 'public_stamps'
-- Note: Buckets must be created via the Dashboard manually if they don't exist.

-- Public Read Access
CREATE POLICY "Public Access to Buckets"
ON storage.objects FOR SELECT
USING ( bucket_id IN ('stamps', 'templates', 'assets', 'public_stamps') );

-- Authenticated Upload/Update/Delete (for Admin Panel)
CREATE POLICY "Authenticated Insert"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id IN ('stamps', 'templates', 'assets', 'public_stamps') );

CREATE POLICY "Authenticated Update"
ON storage.objects FOR UPDATE
TO authenticated
USING ( bucket_id IN ('stamps', 'templates', 'assets', 'public_stamps') );

CREATE POLICY "Authenticated Delete"
ON storage.objects FOR DELETE
TO authenticated
USING ( bucket_id IN ('stamps', 'templates', 'assets', 'public_stamps') );
`;
