
export const PUBLIC_SCHEMA_DDL = `
-- 1. PROFILES
CREATE TABLE IF NOT EXISTS public.profiles (
    id text PRIMARY KEY,
    email text,
    full_name text,
    role text DEFAULT 'user',
    tier text DEFAULT 'Free',
    egg_balance jsonb DEFAULT '{"mystery": 0, "premium": 0, "standard": 3}'::jsonb,
    status text DEFAULT 'active',
    created_at timestamptz DEFAULT now(),
    last_seen timestamptz DEFAULT now(),
    CONSTRAINT profiles_status_check CHECK (status IN ('active', 'inactive', 'banned', 'pending', 'suspended'))
);

-- 2. DROPS
CREATE TABLE IF NOT EXISTS public.drops (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  title text,
  description text,
  status text,
  egg_price int default 0,
  bundle_price int default 0,
  max_supply int,
  artist_id text,
  artist_name text, -- Added for explicit artist display
  banner_path text,
  start_at timestamptz,
  end_at timestamptz,
  created_at timestamptz DEFAULT now()
);

-- 3. STAMPS
CREATE TABLE IF NOT EXISTS public.stamps (
  id bigint generated by default as identity primary key,
  external_id text unique,
  name text,
  slug text,
  rarity text,
  status text,
  collection text,
  artist_id text,
  artist_name text, -- Added for explicit artist display
  art_path text,
  price_eggs int default 0,
  edition_count int default 0,
  is_drop_only boolean default false,
  design_config jsonb,
  created_at timestamptz default now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_stamps_external_id ON public.stamps (external_id);

-- 4. BROADCASTS
CREATE TABLE IF NOT EXISTS public.broadcasts (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text,
  subject text,
  channels text[],
  audience_segment text,
  audience_size int default 0,
  scheduled_at timestamptz,
  status text default 'draft',
  stats jsonb default '{"delivered":0, "opened":0, "clicked":0, "failed":0}'::jsonb,
  created_at timestamptz DEFAULT now()
);

-- 5. PROMOS
CREATE TABLE IF NOT EXISTS public.promos (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text,
  code text,
  type text,
  status text default 'draft',
  description text,
  value jsonb,
  start_at timestamptz,
  end_at timestamptz,
  usage_count int default 0,
  created_at timestamptz DEFAULT now()
);

-- 6. CARDS
CREATE TABLE IF NOT EXISTS public.cards (
    id text PRIMARY KEY,
    owner_id text,
    data jsonb,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 7. TRANSACTIONS
CREATE TABLE IF NOT EXISTS public.transactions (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    profile_id text REFERENCES public.profiles(id),
    amount numeric,
    currency text,
    status text,
    description text,
    created_at timestamptz DEFAULT now()
);

-- 8. TICKETS
CREATE TABLE IF NOT EXISTS public.tickets (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    profile_id text REFERENCES public.profiles(id),
    subject text,
    status text,
    priority text,
    source text,
    tags text[],
    created_at timestamptz DEFAULT now()
);

-- 9. TICKET MESSAGES (Virtual table for support chat)
CREATE TABLE IF NOT EXISTS public.ticket_messages (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    ticket_id uuid REFERENCES public.tickets(id),
    sender_type text,
    sender_id text,
    body text,
    created_at timestamptz DEFAULT now()
);

-- 10. ACTIVITY LOGS
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id text,
    action_type text,
    description text,
    created_at timestamptz DEFAULT now()
);

-------------------------------------------------------------------------------
-- ROW LEVEL SECURITY (RLS) & PERMISSIONS
-------------------------------------------------------------------------------

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stamps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.broadcasts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ticket_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

-- Grant access to authenticated users (The Dashboard Admins)
-- Note: In a real production app, you would check for role='admin' in a policy.
-- For this setup, we assume 'authenticated' means logged in via Supabase Auth.

CREATE POLICY "Enable read access for all users" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.profiles FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for users based on email" ON public.profiles FOR UPDATE USING (auth.uid()::text = id);

-- Permissive policies for the Control Tower (Admin Dashboard)
CREATE POLICY "Admin All Access Drops" ON public.drops FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin All Access Stamps" ON public.stamps FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin All Access Broadcasts" ON public.broadcasts FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin All Access Promos" ON public.promos FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin All Access Cards" ON public.cards FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin All Access Transactions" ON public.transactions FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin All Access Tickets" ON public.tickets FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin All Access Ticket Messages" ON public.ticket_messages FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin All Access Logs" ON public.activity_logs FOR ALL TO authenticated USING (true);

-------------------------------------------------------------------------------
-- STORAGE POLICIES (Run this to fix "Connecting..." issues)
-------------------------------------------------------------------------------
-- These policies apply to the 'storage.objects' table in the 'storage' schema.
-- You must create the buckets ('stamps', 'templates', 'assets', 'public_stamps') in the dashboard first.

-- 1. Public Read Access
CREATE POLICY "Public Access to Buckets"
ON storage.objects FOR SELECT
USING ( bucket_id IN ('stamps', 'templates', 'assets', 'public_stamps') );

-- 2. Authenticated Upload/Update/Delete
CREATE POLICY "Authenticated Insert"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id IN ('stamps', 'templates', 'assets', 'public_stamps') );

CREATE POLICY "Authenticated Update"
ON storage.objects FOR UPDATE
TO authenticated
USING ( bucket_id IN ('stamps', 'templates', 'assets', 'public_stamps') );

CREATE POLICY "Authenticated Delete"
ON storage.objects FOR DELETE
TO authenticated
USING ( bucket_id IN ('stamps', 'templates', 'assets', 'public_stamps') );
`;
