
export const PUBLIC_SCHEMA_DDL = `
-- 1) TABLE: profiles
CREATE TABLE public.profiles (
    id text PRIMARY KEY,
    email text,
    full_name text,
    role text DEFAULT 'user'::text,
    tier text DEFAULT 'Free'::text,
    egg_balance jsonb DEFAULT '{"mystery": 0, "premium": 0, "standard": 3}'::jsonb,
    status text DEFAULT 'active'::text,
    created_at timestamptz DEFAULT now(),
    last_seen timestamptz DEFAULT now(),
    CONSTRAINT profiles_status_check CHECK (status IN ('active', 'inactive', 'banned', 'pending', 'suspended'))
);

-- 2) TABLE: cards
CREATE TABLE public.cards (
    id text PRIMARY KEY,
    data jsonb,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    owner_id text
);

-- 3) TABLE: transactions (Revenue)
CREATE TABLE public.transactions (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    profile_id text REFERENCES public.profiles(id),
    amount numeric,
    currency text,
    status text,
    description text,
    created_at timestamptz DEFAULT now()
);

-- 4) TABLE: tickets (Support)
CREATE TABLE public.tickets (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    profile_id text REFERENCES public.profiles(id),
    subject text,
    status text,
    priority text,
    created_at timestamptz DEFAULT now()
);

-- 5) TABLE: activity_logs (Real-time feed)
CREATE TABLE public.activity_logs (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id text REFERENCES public.profiles(id),
    action_type text,
    description text,
    created_at timestamptz DEFAULT now()
);

-- 6) TABLE: drops
CREATE TABLE public.drops (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  title text,
  description text,
  status text,
  egg_price int default 0,
  bundle_price int default 0,
  max_supply int,
  artist_id text, -- Legacy/Reference ID
  artist_name text, -- Free-form text for display
  banner_path text,
  start_at timestamptz,
  end_at timestamptz,
  created_at timestamptz DEFAULT now()
);

-- 7) TABLE: stamps
CREATE TABLE public.stamps (
  id bigint generated by default as identity primary key,
  external_id text unique,
  name text,
  slug text,
  rarity text,
  status text, -- draft, ready, active, archived
  collection text,
  artist_id text, -- Legacy/Reference ID
  artist_name text, -- Free-form text for display
  art_path text, -- URL to the file in storage
  price_eggs int default 0,
  edition_count int default 0, -- Max supply for this stamp
  is_drop_only boolean default false,
  design_config jsonb, -- Playground settings
  created_at timestamptz default now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_stamps_external_id ON public.stamps (external_id);

-- 8) TABLE: broadcasts
CREATE TABLE public.broadcasts (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text,
  subject text,
  channels text[], -- array of strings e.g. ['email', 'push']
  audience_segment text,
  audience_size int default 0,
  scheduled_at timestamptz,
  status text default 'draft',
  stats jsonb default '{"delivered":0, "opened":0, "clicked":0, "failed":0}'::jsonb,
  created_at timestamptz DEFAULT now()
);

-- 9) TABLE: promos
CREATE TABLE public.promos (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text,
  code text,
  type text,
  status text default 'draft',
  description text,
  value jsonb,
  start_at timestamptz,
  end_at timestamptz,
  usage_count int default 0,
  created_at timestamptz DEFAULT now()
);

------------------------------------------------------------------
-- MIGRATION UTILITIES (Run these in Supabase SQL Editor if needed)
------------------------------------------------------------------

-- 1) Add Status Column Safely (if missing)
-- ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS status text;
-- UPDATE public.profiles SET status = 'active' WHERE status IS NULL;
-- ALTER TABLE public.profiles ALTER COLUMN status SET DEFAULT 'active';

-- 2) Add/Update Check Constraint
-- ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_status_check;
-- ALTER TABLE public.profiles ADD CONSTRAINT profiles_status_check CHECK (status IN ('active', 'inactive', 'banned', 'pending', 'suspended'));

-- 3) ARTIST NAME MIGRATION (Crucial for saving names without UUID errors)
-- ALTER TABLE public.drops ADD COLUMN IF NOT EXISTS artist_name text;
-- ALTER TABLE public.stamps ADD COLUMN IF NOT EXISTS artist_name text;
-- UPDATE public.drops SET artist_name = COALESCE(artist_name, artist_id) WHERE artist_id IS NOT NULL AND artist_name IS NULL;
-- UPDATE public.stamps SET artist_name = COALESCE(artist_name, artist_id) WHERE artist_id IS NOT NULL AND artist_name IS NULL;

-- 4) RLS POLICIES (If RLS is enabled)
-- GRANT USAGE ON SCHEMA public TO authenticated;
-- GRANT SELECT, INSERT, UPDATE ON public.drops, public.stamps TO authenticated;
-- CREATE POLICY "drops_read_all" ON public.drops FOR SELECT TO authenticated USING (true);
-- CREATE POLICY "drops_insert_all" ON public.drops FOR INSERT TO authenticated WITH CHECK (true);
-- CREATE POLICY "stamps_read_all" ON public.stamps FOR SELECT TO authenticated USING (true);
-- CREATE POLICY "stamps_insert_all" ON public.stamps FOR INSERT TO authenticated WITH CHECK (true);
`;
